keycloak:
  url: http://localhost:8443
  admin:
    username: admin
    password: admin
  realm: master
  client-id: admin-cli
spring:
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/health-check
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@149.156.138.232:1521:orcl
    username: akh
    password: akh2023

notification:
  service: mock # [mock, sync, async]

storage:
  type: inMemory #[inMemory, cloud, local]
