server:
  port: 8080 # select available port on your pc, or left 8080 which is used in docker images
  servlet:
    context-path: /api/domain-service

spring:
  application:
    name: domain-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, readinessState
  endpoint:
    health:
      enabled: true
  server:
    port: 8050
