spring:
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/health-check
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@149.156.138.232:1521:orcl
    username: akh
    password: akh2023

notification:
  service: async # [mock, sync, async]
