CREATE TABLE ADDRESS
(
    ADDRESS_ID       INT         NOT NULL,
    CITY             VARCHAR(50) NOT NULL,
    HOUSE_NUMBER     VARCHAR(10) NOT NULL,
    APARTMENT_NUMBER VARCHAR(10),
    POSTAL_CODE      VARCHAR(10) NOT NULL,
    POST             VARCHAR(50) NOT NULL,
    COUNTY           VARCHAR(50) NOT NULL,
    PROVINCE         VARCHAR(50) NOT NULL,
    PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID INT         NOT NULL,
    NAME          VARCHAR(40) NOT NULL,
    ADDRESS_ID    INT         NOT NULL,
    PRIMARY KEY (DEPARTMENT_ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID)
);

CREATE TABLE PERSON
(
    PERSON_ID   VARCHAR(40) NOT NULL,
    FIRST_NAME  VARCHAR(40) NOT NULL,
    SECOND_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (PERSON_ID)
);

CREATE TABLE DOCTOR
(
    DOCTOR_ID      VARCHAR(40) NOT NULL,
    DEPARTMENT_ID  INT         NOT NULL,
    SPECIALIZATION VARCHAR(25) NOT NULL,
    PRIMARY KEY (DOCTOR_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES PERSON (PERSON_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE RECEPTIONIST
(
    RECEPTIONIST_ID VARCHAR(40) NOT NULL,
    DEPARTMENT_ID   INT         NOT NULL,
    PRIMARY KEY (RECEPTIONIST_ID),
    FOREIGN KEY (RECEPTIONIST_ID) REFERENCES PERSON (PERSON_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE PATIENT
(
    PATIENT_ID   VARCHAR(40)  NOT NULL,
    PESEL        VARCHAR(11)  NOT NULL,
    PHONE_NUMBER VARCHAR(9)   NOT NULL,
    ADDRESS_ID   INT          NOT NULL,
    GENDER       VARCHAR2(10) NOT NULL,
    CONSTRAINT CHECK_GENDER CHECK (GENDER IN ('MALE', 'FEMALE')),
    PRIMARY KEY (PATIENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PERSON (PERSON_ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ADDRESS_ID)
);

CREATE TABLE TEST
(
    TEST_ID       INT           NOT NULL,
    PATIENT_ID    VARCHAR(40)   NOT NULL,
    DEPARTMENT_ID INT           NOT NULL,
    TYPE          VARCHAR(30)   NOT NULL,
    DESCRIPTION   VARCHAR(1000) NOT NULL,
    PRIMARY KEY (TEST_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID)
);

CREATE TABLE TEST_RESULT
(
    TEST_RESULT_ID INT           NOT NULL,
    TEST_ID        INT           NOT NULL,
    DESCRIPTION    VARCHAR(8000) NOT NULL,
    PRIMARY KEY (TEST_RESULT_ID),
    FOREIGN KEY (TEST_ID) REFERENCES TEST (TEST_ID)
);

CREATE TABLE ADMINISTRATOR
(
    ADMINISTRATOR_ID VARCHAR(40) NOT NULL,
    DEPARTMENT_ID    INT         NOT NULL,
    PRIMARY KEY (ADMINISTRATOR_ID),
    FOREIGN KEY (ADMINISTRATOR_ID) REFERENCES PERSON (PERSON_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE RATING
(
    RATING_ID   INT         NOT NULL,
    PATIENT_ID  VARCHAR(40) NOT NULL,
    DOCTOR_ID   VARCHAR(40) NOT NULL,
    GRADE       INT         NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PRIMARY KEY (RATING_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (DOCTOR_ID)
);

CREATE TABLE SCHEDULE
(
    SCHEDULE_ID     INT         NOT NULL,
    DOCTOR_ID       VARCHAR(40) NOT NULL,
    START_DATE_TIME DATE        NOT NULL,
    END_DATE_TIME   DATE        NOT NULL,
    PRIMARY KEY (SCHEDULE_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (DOCTOR_ID)
);

CREATE TABLE APPOINTMENT
(
    APPOINTMENT_ID   INT         NOT NULL,
    DOCTOR_ID        VARCHAR(40) NOT NULL,
    PATIENT_ID       VARCHAR(40) NOT NULL,
    DEPARTMENT_ID    INT         NOT NULL,
    APPOINTMENT_DATE DATE        NOT NULL,
    COMMENTS         VARCHAR(8000),
    CABINET_NUMBER   INT         NOT NULL,
    PRIMARY KEY (APPOINTMENT_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (DOCTOR_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PATIENT_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE TREATMENT
(
    TREATMENT_ID   INT NOT NULL,
    APPOINTMENT_ID INT NOT NULL,
    DIAGNOSIS      VARCHAR(8000),
    RECOMMENDATION VARCHAR(8000),
    PRIMARY KEY (TREATMENT_ID),
    FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT (APPOINTMENT_ID)
);

CREATE TABLE PRESCRIPTION
(
    PRESCRIPTION_ID INT NOT NULL,
    TREATMENT_ID    INT NOT NULL,
    CODE            VARCHAR(50),
    DESCRIPTION     VARCHAR(50),
    EXPIRATION_DATE DATE,
    PRIMARY KEY (PRESCRIPTION_ID),
    FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT (TREATMENT_ID)
);

CREATE TABLE REFERRAL
(
    REFERRAL_ID     INT         NOT NULL,
    TREATMENT_ID    INT         NOT NULL,
    TYPE            VARCHAR(50) NOT NULL,
    EXPIRATION_DATE DATE,
    PRIMARY KEY (REFERRAL_ID),
    FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT (TREATMENT_ID)
);