CREATE TABLE ADDRESS
(
    ID               VARCHAR(40) NOT NULL,
    CITY             VARCHAR(50) NOT NULL,
    HOUSE_NUMBER     VARCHAR(10) NOT NULL,
    APARTMENT_NUMBER VARCHAR(10),
    POSTAL_CODE      VARCHAR(10) NOT NULL,
    POST             VARCHAR(50) NOT NULL,
    COUNTY           VARCHAR(50) NOT NULL,
    PROVINCE         VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DEPARTMENT
(
    ID                 VARCHAR(40) NOT NULL,
    NAME               VARCHAR(40) NOT NULL,
    ADDRESS_ID         VARCHAR(40) NOT NULL,
    NUMBER_OF_CABINETS INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);

CREATE TABLE PERSON
(
    ID          VARCHAR(40) NOT NULL,
    FIRST_NAME  VARCHAR(40) NOT NULL,
    SECOND_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DOCTOR
(
    PERSON_ID      VARCHAR(40) NOT NULL,
    DEPARTMENT_ID  VARCHAR(40) NOT NULL,
    SPECIALIZATION VARCHAR(25) NOT NULL,
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE RECEPTIONIST
(
    PERSON_ID          VARCHAR(40) NOT NULL,
    DEPARTMENT_ID      VARCHAR(40) NOT NULL,
    DATE_OF_EMPLOYMENT DATE        NOT NULL,
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE PATIENT
(
    PERSON_ID    VARCHAR(40)  NOT NULL,
    PESEL        VARCHAR(11)  NOT NULL,
    PHONE_NUMBER VARCHAR(9)   NOT NULL,
    ADDRESS_ID   VARCHAR(40)  NOT NULL,
    GENDER       VARCHAR2(10) NOT NULL,
    CONSTRAINT CHECK_GENDER CHECK (GENDER IN ('MALE', 'FEMALE')),
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);

CREATE TABLE TEST
(
    ID            VARCHAR(40) NOT NULL,
    PATIENT_ID    VARCHAR(40) NOT NULL,
    DEPARTMENT_ID VARCHAR(40) NOT NULL,
    TYPE          VARCHAR(30) NOT NULL,
    DESCRIPTION   VARCHAR(1000) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PERSON_ID)
);

CREATE TABLE TEST_RESULT
(
    ID          VARCHAR(40) NOT NULL,
    TEST_ID     VARCHAR(40) NOT NULL,
    DESCRIPTION VARCHAR(8000) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (TEST_ID) REFERENCES TEST (ID)
);

CREATE TABLE ADMINISTRATOR
(
    PERSON_ID     VARCHAR(40) NOT NULL,
    DEPARTMENT_ID VARCHAR(40) NOT NULL,
    PRIMARY KEY (PERSON_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE RATING
(
    ID          VARCHAR(40) NOT NULL,
    PATIENT_ID  VARCHAR(40) NOT NULL,
    DOCTOR_ID   VARCHAR(40) NOT NULL,
    GRADE       INT         NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PRIMARY KEY (ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PERSON_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (PERSON_ID)
);

CREATE TABLE SCHEDULE
(
    ID              VARCHAR(40) NOT NULL,
    DOCTOR_ID       VARCHAR(40) NOT NULL,
    START_DATE_TIME DATE        NOT NULL,
    END_DATE_TIME   DATE        NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (PERSON_ID)
);

CREATE TABLE APPOINTMENT
(
    ID               VARCHAR(40) NOT NULL,
    DOCTOR_ID        VARCHAR(40) NOT NULL,
    PATIENT_ID       VARCHAR(40) NOT NULL,
    DEPARTMENT_ID    VARCHAR(40) NOT NULL,
    APPOINTMENT_DATE DATE        NOT NULL,
    COMMENTS         VARCHAR(8000),
    CABINET_NUMBER   INT         NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (PERSON_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (PERSON_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID)
);

CREATE TABLE TREATMENT
(
    ID             VARCHAR(40) NOT NULL,
    APPOINTMENT_ID VARCHAR(40) NOT NULL,
    DIAGNOSIS      VARCHAR(8000),
    RECOMMENDATION VARCHAR(8000),
    PRIMARY KEY (ID),
    FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT (ID)
);

CREATE TABLE PRESCRIPTION
(
    ID              VARCHAR(40) NOT NULL,
    TREATMENT_ID    VARCHAR(40) NOT NULL,
    CODE            VARCHAR(50),
    DESCRIPTION     VARCHAR(50),
    EXPIRATION_DATE DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT (ID)
);

CREATE TABLE REFERRAL
(
    ID              VARCHAR(40) NOT NULL,
    TREATMENT_ID    VARCHAR(40) NOT NULL,
    TYPE            VARCHAR(30) NOT NULL,
    EXPIRATION_DATE DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT (ID)
);