apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.app.name}}
spec:
  hosts:
    - '*'
  gateways:
    - {{.Values.gateway}}
  http:
    - match:
        - uri:
            prefix: /api/domain-service
      route:
        - destination:
            host: {{.Values.app.name}}
            port:
              number: {{.Values.service.port}}